### PR TITLE
a mess of changes about robustness and speed

### PR DESCRIPTION
**Pull request by gdh1995**
This PR includes 3 commit for different purposes:
* the first one is for safer code
  * in case that mousewatcher thread wants to join the main thread when the program is exiting.
  * I once met the case and my mouse got stuck for seconds.
* the second one is for speed:
  * there're tons of mousemove events grabbed by mousewatcher,
  * in this case it should not do works across threads, so that CPU utilization may be lower.
* the third is a new settting item "AutoUpdate" (just for my personal opinion)
  * I think one program should allow users to decide whether or not to auto-update itself
  * Since this repo is bfritscher/carnac, so I set the default of AutoUpdate `false`.

### CODE REVIEW

**Comment by gdh1995** [comment]
If the "AutoUpdate" is not a good practice, please let me know and I'll delete this commit from this PR.

**Comment by bfritscher** [comment]
Hi! thanks for all your commits. The mouse tracking was a first quick fix and learn the code base. It now seems that there is a better library https://github.com/gmamaladze/globalmousekeyhook to track also middle click, and mouse wheel and have access to the  eventargs. This would allow 
 to see if a ctrl key is pressed with the mouse and display it with the keys. So I plan to switch to this version.

**Comment by gdh1995** [comment]
That's cool. Thanks for your work.

And what about adding an option to control "auto update"?

**Comment by bfritscher** [comment]
Hi I have done some cleanup added, new feature and the new mouse support. If you have time to give it a try and provide any feedback. Thanks https://github.com/bfritscher/carnac/releases/tag/v3-beta

**Pull request closed without merging**
